### ISSUE TITLE
A Couple of Questions

### ISSUE THREAD

**Issue by elliotberry** [iflowfor8hours/6112884-pro-micro-controller#1]
Hi Matt,

First off, I want to thank you for providing this awesome guide and its accompanying blog post. Soarer has been great with his documentation over on the forums, but you were really able to provide a great companion to them with an introduction to Soarer's controller, and the IBM 6112884 in particular. I have a couple questions, If you don't mind answering them. I thought I would post here in case other people come looking on this repo.
- Soarer's `scas` tool issues an error at the `matrix` command when I attempt to compile your `.sc` files. I am right in assuming that that's just there to provide a visual reference for Pro Micro pins and their on-board counterparts? If I want to re-compile your `.sc` files, can I remove this block?
- As you're aware, soarer's [https://geekhack.org/index.php?PHPSESSID=bf30e0gktda41qk9omijpv5oaahu0ak2&action=dlattach;topic=50437.0;attach=50921;image](spec of the 6112884 chip) has pointed out the pins corresponding with `pc7` and `pb7`. Similarly, your `6112884AllKeysAssigned.sc` file shows the pins you swapped out to make the jump from the Teensy to the Pro Micro clone. So, I assume there's a way to config the `.sc` files to use different pins for the same functions on Teensys? I can't find this on the forums.
- And, finally, the reason I ask that is because I can't get my space bar and a couple of function keys working! No `hid_listen` output, nothing, and I used identical hardware to you! As I mentioned, I've been unable to compile the `.sc` files, so I tried flashing both compiled scb files you had, and while `micro_6112884AllKeysAssigned.scb` didn't work at all, `6112884AllKeysAssigned.scb` did, but with the above issue. `6112884AllKeysAssigned.sc` has the space bar aligned with `pb7` in `matrix`, so maybe there's a relation there?

Also a comment - I have a couple notes about doing this with software in MacOSX, so I can contribute them to the readme if you'd like! 

Thanks a bunch!

Elliot

**Comment by iflowfor8hours** [comment]
No worries, I'm glad this repo is useful to someone!

I ran the complier after a clean checkout of the repo and it seems to have created the .scb file just fine, so I'm not sure what is wrong with running `scas`, can you post the output after a clean checkout and just run `./soarer/tools/scas 6112884_files/micro_6112884AllKeysAssigned.sc 6112884_files/micro_6112884AllKeysAssigned.scb` and see if it fails or creates the binary?

That `micro_6112884AllKeysAssigned.sc` file should compile just fine as far as I know, I just tried it and it still works, so I would be interested to see where it is bailing.

The reason for the changes between my `micro_6112884AllKeysAssigned.sc` and the original `6112884AllKeysAssigned.sc` was because of the way the pins are labeled in soarer's assembler, specfically for the teensy and not for the pro micro. I have never tried to compile his tools from source. Which controller are you using?

I think the problem you're having won't be too crazy to debug and hopefully fix. It sounds like you're using a teensy so you should stick to modifying the `6112884AllKeysAssigned.sc` file, but we probably need to figure out what is wrong with compilation first. Post the errors you're getting and we can go from there. Are any of the other keys in the column or row that space is on also not working? 

I would definitely appreciate contributions on getting this to work on MacOSX if it's no sweat off your back to show how you got your environment set up. 
Thanks,
matt.

**Comment by elliotberry** [comment]
Yeah, I actually figured out half of this stuff already haha. Weirdly, I'm using a ATmega32U4 Pro Micro clone that I think is identical to yours (http://www.ebay.com/itm/121873186141?_trksid=p2057872.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT), but I'm having to use the teensy config. Maybe I'm paying the cheap chinese electronic tax - you probably got the Sparkfun one?

The compiling issues I was having was with Soarer's 1.1 scas tool, and when I switched to 1.20 beta it started working, pretty weird. These are probably OSX quirks. I started sloppily documenting some stuff [here](https://github.com/elliotberry/6112884-pro-micro-controller), but I can clean it up and can commit it as a different section on your readme. 

Thanks so much for your help!
